# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql
  database: job_postings_development
  username: root
  password: password
  host: localhost

test:
  adapter: mysql
  database: job_postings_test
  username: root
  password: password
  host: localhost

production:
  adapter: mysql
  database: job_postings_production
  username: root
  password: password
  host: localhost
