# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

JobPosting.create!(job_ID: '123456', keyword: 'rails', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Shopify')
JobPosting.create!(job_ID: '555555', keyword: 'node.js', city: 'Montreal', province: 'Quebec', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '109234', keyword: 'rails', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Younility')
JobPosting.create!(job_ID: '234323', keyword: 'ember.js', city: 'Vancouver', province: 'British Columbia', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '934343', keyword: 'django', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Mitel')
JobPosting.create!(job_ID: '079092', keyword: 'cake.php', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Ebay')
JobPosting.create!(job_ID: '220343', keyword: 'NetBeans', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Government of Canada')
JobPosting.create!(job_ID: '123456', keyword: 'rails', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Shopify')
JobPosting.create!(job_ID: '555555', keyword: 'node.js', city: 'Montreal', province: 'Quebec', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '109234', keyword: 'rails', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Younility')
JobPosting.create!(job_ID: '234323', keyword: 'ember.js', city: 'Vancouver', province: 'British Columbia', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '934343', keyword: 'django', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Mitel')
JobPosting.create!(job_ID: '079092', keyword: 'cake.php', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Ebay')
JobPosting.create!(job_ID: '220343', keyword: 'NetBeans', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Government of Canada')
JobPosting.create!(job_ID: '234235', keyword: 'rails', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Shopify')
JobPosting.create!(job_ID: '364246', keyword: 'node.js', city: 'Montreal', province: 'Quebec', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '146146', keyword: 'rails', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Younility')
JobPosting.create!(job_ID: '336836', keyword: 'ember.js', city: 'Vancouver', province: 'British Columbia', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '146146', keyword: 'django', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Mitel')
JobPosting.create!(job_ID: '123462', keyword: 'cake.php', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Ebay')
JobPosting.create!(job_ID: '634624', keyword: 'NetBeans', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Government of Canada')
JobPosting.create!(job_ID: '146146', keyword: 'rails', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Shopify')
JobPosting.create!(job_ID: '836656', keyword: 'node.js', city: 'Montreal', province: 'Quebec', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '725702', keyword: 'rails', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Younility')
JobPosting.create!(job_ID: '914614', keyword: 'ember.js', city: 'Vancouver', province: 'British Columbia', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '752700', keyword: 'django', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Mitel')
JobPosting.create!(job_ID: '146909', keyword: 'cake.php', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Ebay')
JobPosting.create!(job_ID: '863686', keyword: 'NetBeans', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Government of Canada')
JobPosting.create!(job_ID: '090976', keyword: 'rails', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Shopify')
JobPosting.create!(job_ID: '945145', keyword: 'node.js', city: 'Montreal', province: 'Quebec', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '681461', keyword: 'rails', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Younility')
JobPosting.create!(job_ID: '912457', keyword: 'ember.js', city: 'Vancouver', province: 'British Columbia', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '161463', keyword: 'django', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Mitel')
JobPosting.create!(job_ID: '146166', keyword: 'cake.php', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Ebay')
JobPosting.create!(job_ID: '614639', keyword: 'NetBeans', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Government of Canada')
JobPosting.create!(job_ID: '014631', keyword: 'rails', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Shopify')
JobPosting.create!(job_ID: '963406', keyword: 'node.js', city: 'Montreal', province: 'Quebec', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '061451', keyword: 'rails', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Younility')
JobPosting.create!(job_ID: '861495', keyword: 'ember.js', city: 'Vancouver', province: 'British Columbia', country: 'Canada', company: 'IBM')
JobPosting.create!(job_ID: '969145', keyword: 'django', city: 'Ottawa', province: 'Ontario', country: 'Canada', company: 'Mitel')
JobPosting.create!(job_ID: '069456', keyword: 'cake.php', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Ebay')
JobPosting.create!(job_ID: '987142', keyword: 'NetBeans', city: 'Toronto', province: 'Ontario', country: 'Canada', company: 'Government of Canada')